Improve install instructions
PrefectHQ/prefect-gcp pull request #18
Opened 2022-05-10 15:49 UTC by ahuang11

## Summary
Based on
https://prefect-community.slack.com/archives/CL09KU1K7/p1652193557583229

Fixed so it doesn't just raise the `SecretManagerServiceClient' is not defined` error now, and now properly raises
```
09:47:34.668 | ERROR   | Flow run 'acoustic-dragon' - Using `prefect_gcp.secret_manager` requires `pip install prefect_gcp[secret_manager]`
```
However, not sure if it's too hidden within the logs?

```
09:47:34.650 | INFO    | prefect.engine - Created flow run 'acoustic-dragon' for flow 'example-get-client-flow'
09:47:34.650 | INFO    | Flow run 'acoustic-dragon' - Using task runner 'ConcurrentTaskRunner'
09:47:34.657 | WARNING | Flow run 'acoustic-dragon' - No default storage is configured on the server. Results from this flow run will be stored in a temporary directory in its runtime environment.
09:47:34.668 | ERROR   | Flow run 'acoustic-dragon' - Using `prefect_gcp.secret_manager` requires `pip install prefect_gcp[secret_manager]`
Traceback (most recent call last):
  File "/Users/andrew/Applications/python/prefect-gcp/prefect_gcp/credentials.py", line 48, in inner
    return func(*args, **kwargs)
  File "/Users/andrew/Applications/python/prefect-gcp/prefect_gcp/credentials.py", line 290, in get_secret_manager_client
    secret_manager_client = SecretManagerServiceClient(credentials=credentials)
NameError: name 'SecretManagerServiceClient' is not defined
09:47:34.669 | ERROR   | Flow run 'acoustic-dragon' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/andrew/Applications/python/orion/src/prefect/engine.py", line 467, in orchestrate_flow_run
    result = await run_sync_in_worker_thread(flow_call)
  File "/Users/andrew/Applications/python/orion/src/prefect/utilities/asyncio.py", line 52, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(context.run, call, cancellable=True)
  File "/Users/andrew/mambaforge/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/andrew/mambaforge/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/andrew/mambaforge/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/var/folders/tb/fksvh8ms2hl5xnzwrftnx66r0000gq/T/ipykernel_26995/3185811317.py", line 6, in example_get_client_flow
    client = GcpCredentials(
  File "/Users/andrew/Applications/python/prefect-gcp/prefect_gcp/credentials.py", line 48, in inner
    return func(*args, **kwargs)
  File "/Users/andrew/Applications/python/prefect-gcp/prefect_gcp/credentials.py", line 290, in get_secret_manager_client
    secret_manager_client = SecretManagerServiceClient(credentials=credentials)
NameError: name 'SecretManagerServiceClient' is not defined
09:47:34.694 | ERROR   | Flow run 'acoustic-dragon' - Finished in state Failed('Flow run encountered an exception.')
Failed(message='Flow run encountered an exception.', type=FAILED, result=NameError("name 'SecretManagerServiceClient' is not defined"), flow_run_id=a042ac12-a3c3-4121-947c-35a133ae694d)
```

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-gcp/blob/main/CHANGELOG.md)

2022-05-10 16:05 UTC, ahuang11 commented
Results in:
```
10:04:21.566 | INFO    | prefect.engine - Created flow run 'enchanted-stingray' for flow 'example-get-client-flow'
10:04:21.566 | INFO    | Flow run 'enchanted-stingray' - Using task runner 'ConcurrentTaskRunner'
10:04:21.573 | WARNING | Flow run 'enchanted-stingray' - No default storage is configured on the server. Results from this flow run will be stored in a temporary directory in its runtime environment.
10:04:21.584 | ERROR   | Flow run 'enchanted-stingray' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/andrew/Applications/python/prefect-gcp/prefect_gcp/credentials.py", line 48, in inner
    return func(*args, **kwargs)
  File "/Users/andrew/Applications/python/prefect-gcp/prefect_gcp/credentials.py", line 291, in get_secret_manager_client
    secret_manager_client = SecretManagerServiceClient(credentials=credentials)
NameError: name 'SecretManagerServiceClient' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrew/Applications/python/orion/src/prefect/engine.py", line 467, in orchestrate_flow_run
    result = await run_sync_in_worker_thread(flow_call)
  File "/Users/andrew/Applications/python/orion/src/prefect/utilities/asyncio.py", line 52, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(context.run, call, cancellable=True)
  File "/Users/andrew/mambaforge/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/andrew/mambaforge/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/andrew/mambaforge/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/var/folders/tb/fksvh8ms2hl5xnzwrftnx66r0000gq/T/ipykernel_30459/3185811317.py", line 6, in example_get_client_flow
    client = GcpCredentials(
  File "/Users/andrew/Applications/python/prefect-gcp/prefect_gcp/credentials.py", line 50, in inner
    raise ImportError(
ImportError: Using `prefect_gcp.secret_manager` requires `pip install prefect_gcp[secret_manager]`
10:04:21.596 | ERROR   | Flow run 'enchanted-stingray' - Finished in state Failed('Flow run encountered an exception.')
Failed(message='Flow run encountered an exception.', type=FAILED, result=ImportError('Using `prefect_gcp.secret_manager` requires `pip install prefect_gcp[secret_manager]`'), flow_run_id=f894996a-014b-43fc-94c3-357868434f5d)
```

2022-05-10 20:09 UTC, desertaxle requested changes
Small suggestion to add a little color to the error message.

2022-05-10 20:09 UTC, desertaxle commented on prefect_gcp/credentials.py
>                      f"`pip install prefect_gcp[{key}]`"
```suggestion
                    f"To use prefect_gcp.{key}, install prefect-gcp with the "
                    f"'{key}' extra: `pip install prefect_gcp[{key}]`"
```

2022-05-12 12:49 UTC, desertaxle approved these changes

2022-05-19 20:50 UTC, merged