Fix `list_folders` to keep dots in the middle of the paths
PrefectHQ/prefect-gcp pull request #182
Opened 2023-05-24 09:29 UTC by grf53

There was a bug in the `GcsBucket.list_folders` method, that all the dots(`"."`) in the folder paths were gone in its returned values.
That occurred by `.replace(".", "")` after getting paths. Maybe it is because there is unwanted `"."` if there is a file in the current position (refers to #121). We can use a simple filter, instead.

There was no tests with example blob under a folder named with dots. And there wasn't even the test for `list_folders` for the root. So I added along with the fix.

I am not sure including `""` as one of the result is wanted instead of `"."`. I thought it can be just omitted.

### Example
`bucket` is a `GcsBucket` instance that points a bucket with blobs with paths:
- `"blob.txt"`
- `"base_folder/nested_blob.txt"`
- `"dotted.folder/nested_blob.txt"`
#### Before
```
bucket.list_folders()  # ["", "base_folder", "dottedfolder"]
```

#### After
```
bucket.list_folders()  # ["base_folder", "dotted.folder"]
```

### Checklist

- [x] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-gcp/issues/new/choose) first.
- [x] Includes tests or only affects documentation.
- [x] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [x] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-gcp/blob/main/CHANGELOG.md)

2023-05-25 06:39 UTC, grf53 commented
@ahuang11 @razvanvilceanu Could you review this, kindly? You are the authors of #121, so I think you guys are the best reviewers of this.

2023-05-25 06:56 UTC, razvanvilceanu commented
sure, can you assign it to me?

2023-05-25 07:01 UTC, razvanvilceanu approved these changes

2023-05-25 09:14 UTC, grf53 commented
@razvanvilceanu Thanks! I couldn't request review to you(blocked).

2023-05-25 09:14 UTC, grf53 commented
I am still blocked to proceed with message on this page:
```
Code owner review required
Waiting on code owner review from PrefectHQ/integrations.
This workflow requires approval from a maintainer.
```

@billpalombi Hello, I can see you approved some merged PRs that is required to get approvals of code owners.
If you are a code owner, then I'll be appreciated to you to review this.

2023-05-25 12:05 UTC, billpalombi commented
Hi @grf53, I am not a code owner for this repo, but I will make sure that the right people are aware.

2023-05-25 12:12 UTC, grf53 commented
> I will make sure that the right people are aware.

Thank you so much!

2023-05-25 12:48 UTC, desertaxle reviewed
Thanks for contributing @grf53! This change looks good to me overall. I'm going to QA these changes against a real GCS bucket and I'll approve once I've confirmed everything is working as expected.

2023-05-25 12:48 UTC, desertaxle commented on CHANGELOG.md
> -- Added optional `accelerator_count` property for `VertexAICustomTrainingJob`.
Can you please add this line back?

2023-05-25 13:11 UTC, desertaxle requested changes

2023-05-26 05:25 UTC, grf53 commented
@desertaxle Grateful for your feedbacks! I reflected your suggestions. Please take a look.

2023-05-26 15:44 UTC, desertaxle approved these changes
LGTM!

2023-05-26 18:52 UTC, merged