Optional override for Vertex custom job name
PrefectHQ/prefect-gcp pull request #208
Opened 2023-09-01 13:52 UTC by jeremy-thomas-roc

Add optional parameter to VertexAICustomJob to name jobs. This helps in monorepo situations where all Vertex jobs will just be <repo-name>-<uuid>, which is not very helpful when running lots of scheduled jobs.

### Screenshots

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-gcp/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [X] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [X] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-gcp/blob/main/CHANGELOG.md)

2023-09-11 13:44 UTC, jeremy-thomas-roc commented
@desertaxle Can I get some feedback on this? I believe the failing tests happened when there was a dependency issue of the prefect side, but I am unable to re-run them to verify.

2023-09-18 13:17 UTC, desertaxle commented
@jeremy-thomas-roc I think we could use the existing `name` attribute on the `VertexAICustomJob` job to create more unique names for created jobs. By default, `name` will be the flow run name, which has the added advantage of making it easier to map Vertex AI jobs to flow runs. Let me know if that would work for your use case or it you have any questions on implementation.

2023-09-18 19:41 UTC, jeremy-thomas-roc commented
@desertaxle that works for me, implemented that change

2023-09-18 21:03 UTC, desertaxle commented
@jeremy-thomas-roc That's true that `name` can be `None` if the block is used outside of a deployment. A simple check to see if `name` is set should work. We do something similar in `prefect-azure`. You can see https://github.com/PrefectHQ/prefect-azure/pull/92 as an example.

2023-09-19 14:20 UTC, desertaxle requested changes
Couple of small nits, but otherwise this is good to go!

2023-09-19 14:20 UTC, desertaxle commented on CHANGELOG.md
> + - `job_name` in `VertexAICustomJob` is now based on the flow run name instead of the image repository.
```suggestion
 - Use flow run name for name of created custom jobs - [#208](https://github.com/PrefectHQ/prefect-gcp/pull/208)
```

2023-09-19 14:20 UTC, desertaxle commented on prefect_gcp/aiplatform.py
> +            return f"{repo_name}-{uuid4().hex}"
```suggestion
            base_name = self.name or self.image.split("/")[2]
            return f"{base_name}-{uuid4().hex}"
```

2023-09-19 15:12 UTC, jeremy-thomas-roc commented
@desertaxle suggested changes implemented

2023-09-19 17:28 UTC, merged