Fix Tile Paths for service accounts
PrefectHQ/prefect-gcp pull request #38
Opened 2022-08-04 05:37 UTC by wangjoshuah

## Summary
Allow tildes in path for GCP Credentials

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-gcp/blob/main/CHANGELOG.md)

2022-08-04 15:36 UTC, desertaxle requested changes
Thanks so much for the contribution @wangjoshuah! Would you be able to add a test covering this new functionality?

2022-08-04 19:46 UTC, wangjoshuah commented
@desertaxle added small test cases for getting the file following the pattern from before. Let me know if you think it needs more extensive testing.

2022-08-04 22:36 UTC, ahuang11 commented
I wonder if it's possible to simplify the logic from:
```
if not os.path.exists(os.path.expanduser(service_account_file)):
    raise ValueError("The provided path to the service account is invalid")
elif isinstance(service_account_file, Path):
    service_account_file = service_account_file.expanduser()
else:
    service_account_file = os.path.expanduser(service_account_file)
credentials = Credentials.from_service_account_file(service_account_file)
```
to:
```
service_account_file = Path(service_account_file).expanduser()
if not service_account_file.exists():
    raise ValueError("The provided path to the service account is invalid")
credentials = Credentials.from_service_account_file(service_account_file)
```

2022-09-06 22:07 UTC, ahuang11 approved these changes

2022-09-07 14:50 UTC, desertaxle approved these changes

2022-09-07 14:50 UTC, merged